Customize for me
This is my laptop. There are many like it, but this one is mine.

My laptop is my best friend. It is my life. I must master it as I must
master my life.

My laptop, without me, is useless. Without my laptop, I am useless. I
must configure my laptop true. I must code better than my peers who are
trying to code better than me. I will...

My laptop and I know that what counts in programming is not the amount
of code we write, the cleanliness of it, nor the tests that pass. We
know that it is the impact it has on the world that counts. We will
impact...

My laptop is human, even as I, because it is my life. Thus, I will learn
it as a brother. I will learn its weaknesses, its strengths, its parts,
its accessories, its keyboard and its screen. I will keep my laptop
clean and ready, even as I am clean and ready. We will become part of
each other. We will...

Before myself, I swear this creed. My laptop and I are the innovators of
my country. We are the masters of our world. We are the providers of my
life.

So be it, until laptops are obsolete.

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -30,29 +30,6 @@ append_to_zshrc() {
   fi
 }
 
-trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
-
-set -e
-
-if [ ! -d "$HOME/.bin/" ]; then
-  mkdir "$HOME/.bin"
-fi
-
-if [ ! -f "$HOME/.zshrc" ]; then
-  touch "$HOME/.zshrc"
-fi
-
-# shellcheck disable=SC2016
-append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
-
-case "$SHELL" in
-  */zsh) : ;;
-  *)
-    fancy_echo "Changing your shell to zsh ..."
-      chsh -s "$(which zsh)"
-    ;;
-esac
-
 brew_install_or_upgrade() {
   if brew_is_installed "$1"; then
     if brew_is_upgradable "$1"; then
@@ -113,6 +90,29 @@ gem_install_or_update() {
   fi
 }
 
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
+
+set -e
+
+if [ ! -d "$HOME/.bin/" ]; then
+  mkdir "$HOME/.bin"
+fi
+
+if [ ! -f "$HOME/.zshrc" ]; then
+  touch "$HOME/.zshrc"
+fi
+
+# shellcheck disable=SC2016
+append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
+
+case "$SHELL" in
+  */zsh) : ;;
+  *)
+    fancy_echo "Changing your shell to zsh ..."
+      chsh -s "$(which zsh)"
+    ;;
+esac
+
 if ! command -v brew >/dev/null; then
   fancy_echo "Installing Homebrew ..."
     curl -fsS \
@@ -135,27 +135,29 @@ brew_install_or_upgrade 'zsh'
 brew_install_or_upgrade 'git'
 brew_install_or_upgrade 'postgres'
 brew_launchctl_restart 'postgresql'
-brew_install_or_upgrade 'redis'
-brew_launchctl_restart 'redis'
-brew_install_or_upgrade 'the_silver_searcher'
+brew_install_or_upgrade 'pgcli'
 brew_install_or_upgrade 'vim'
-brew_install_or_upgrade 'ctags'
-brew_install_or_upgrade 'tmux'
-brew_install_or_upgrade 'reattach-to-user-namespace'
-brew_install_or_upgrade 'imagemagick'
-brew_install_or_upgrade 'qt'
 brew_install_or_upgrade 'hub'
 brew_install_or_upgrade 'node'
+brew_install_or_upgrade 'heroku-toolbelt'
+brew_install_or_upgrade 'hub'
+brew_install_or_upgrade 'bfg'
+brew_install_or_upgrade 'tree'
+brew_install_or_upgrade 'watchman'
+brew_install_or_upgrade 'liftoff'
+brew_install_or_upgrade 'carthage'
+brew_install_or_upgrade 'boot2docker'
+brew_install_or_upgrade 'docker'
+
+brew_install_or_upgrade 'openssl'
+brew unlink openssl && brew link openssl --force
+brew_install_or_upgrade 'libyaml'
 
 brew_install_or_upgrade 'rbenv'
 brew_install_or_upgrade 'ruby-build'
 
 # shellcheck disable=SC2016
 append_to_zshrc 'eval "$(rbenv init - --no-rehash zsh)"' 1
-
-brew_install_or_upgrade 'openssl'
-brew unlink openssl && brew link openssl --force
-brew_install_or_upgrade 'libyaml'
 
 ruby_version="$(curl -sSL http://ruby.thoughtbot.com/latest)"
 
@@ -176,12 +178,26 @@ fancy_echo "Configuring Bundler ..."
   number_of_cores=$(sysctl -n hw.ncpu)
   bundle config --global jobs $((number_of_cores - 1))
 
-brew_install_or_upgrade 'heroku-toolbelt'
-
 if ! command -v rcup >/dev/null; then
   brew_tap 'thoughtbot/formulae'
   brew_install_or_upgrade 'rcm'
 fi
+
+brew_tap 'caskroom/cask'
+brew_install_or_upgrade 'brew-cask'
+
+export HOMEBREW_CASK_OPTS="--appdir=/Applications"
+
+brew cask install dropbox
+brew cask install google-chrome
+brew cask install 1password
+brew cask install charles
+brew cask install ios-console
+brew cask install screenhero
+brew cask install spotify
+brew cask install vlc
+brew cask install transmission
+brew cask install virtualbox
 
 if [ -f "$HOME/.laptop.local" ]; then
   . "$HOME/.laptop.local"
